import path from 'path';
import fse from 'fs-extra';
import yaml from 'js-yaml';
import _ from 'lodash';

import { Config, Model, YamlConfig, YamlModel, ModelMap } from './config-types';

const packageJson = require('../../package.json');

export interface WriteConfigOptions {
    dirPath: string;
    config: Config;
}

export async function writeConfig({ dirPath, config }: WriteConfigOptions) {
    const yamlConfig = convertToYamlConfig({ config });
    const filePath = path.join(dirPath, 'stackbit.yaml');
    const yamlString = yaml.dump(yamlConfig);
    const info =
        `# This file was generated by @stackbit/sdk v${packageJson.version}\n` +
        '# To learn more about stackbit.yaml please visit https://www.stackbit.com/docs/stackbit-yaml/\n';
    const data = info + yamlString;
    await fse.outputFile(filePath, data);
}

export function convertToYamlConfig({ config }: { config: Config }): YamlConfig {
    const yamlConfig: YamlConfig = _.cloneDeep(_.omit(config, 'models'));
    if (!_.isEmpty(config.models)) {
        yamlConfig.models = _.reduce(
            config.models,
            (yamlModels: ModelMap, model: Model) => {
                if (model.type === 'image') {
                    return yamlModels;
                }
                const yamlModel = _.omit(model, ['name', '__metadata']) as YamlModel;
                if (yamlModel.type === 'page' && !yamlModel.hideContent && yamlModel.fields) {
                    _.remove(yamlModel.fields, (field) => field.name === 'markdown_content');
                }
                if (yamlModel.type === 'page' && yamlModel.fields) {
                    _.remove(yamlModel.fields, (field) => field.name === (config.pageLayoutKey || 'layout'));
                }
                if (yamlModel.type === 'data' && yamlModel.fields) {
                    _.remove(yamlModel.fields, (field) => field.name === (config.objectTypeKey || 'type'));
                }
                yamlModels[model.name] = yamlModel;
                return yamlModels;
            },
            {}
        );
    }
    return yamlConfig;
}
